name: flutter_langdetect
description: A Flutter package for detecting the language of a given text using character-wise n-gram models
version: 0.0.3
homepage: https://github.com/hiroshi75/flutter_langdetect


publish_to: 'none'


environment:
  sdk: '>=2.17.0 <3.19.1'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.2.0 
  pana: ^0.21.33

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_test:




flutter:
































